apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-producao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-producao
  template:
    metadata:
      labels:
        app: ms-producao
    spec:
      containers:
        - name: ms-producao
          image: 307946636040.dkr.ecr.sa-east-1.amazonaws.com/ms-producao:latest
          ports:
            - containerPort: 8083
          # Adição de variáveis de ambiente
          env:
            - name: DATABASE_DIALECT
              value: "postgres"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: db
            - name: TYPEORM_CONNECTION
              value: "postgres"
            - name: TYPEORM_URL
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: typeorm
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: redis_port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: redis_password
