apiVersion: v1
kind: Service
metadata:
  name: sistema-pagamentos-mock-service
spec:
  type: NodePort
  selector:
    app: sistema-pagamentos-mock
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30003
