apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: producao-dbcredentials
      type: Opaque
      data:
        - objectName: host
          key: host
        - objectName: port
          key: port
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: db
          key: db
        - objectName: typeorm
          key: typeorm
        - objectName: redis_host
          key: redis_host
        - objectName: redis_port
          key: redis_port
        - objectName: redis_password
          key: redis_password
  parameters:
    region: sa-east-1
    objects: |
      - objectName: "arn:aws:secretsmanager:sa-east-1:307946636040:secret:producao-dbcredentials-Rcdms4"
        objectAlias: "producao-dbcredentials"
        jmesPath:
          - path: "host"
            objectAlias: "host"
          - path: "port"
            objectAlias: "port"
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
          - path: "db"
            objectAlias: "db"
          - path: "typeorm"
            objectAlias: "typeorm"
          - path: "redis_host"
            objectAlias: "redis_host"
          - path: "redis_port"
            objectAlias: "redis_port"
          - path: "redis_password"
            objectAlias: "redis_password"
