apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-producao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-producao
  template:
    metadata:
      labels:
        app: ms-producao
    spec:
      containers:
        - name: ms-producao
          image: 307946636040.dkr.ecr.sa-east-1.amazonaws.com/ms-producao:latest
          ports:
            - containerPort: 8083
          env:
            - name: DATABASE_DIALECT
              value: "postgres"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: db_host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: db_port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: db_password
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: producao-dbcredentials
                  key: db_name