apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: producao-dbcredentialsv2
      type: Opaque
      data:
        - objectName: db_host
          key: db_host
        - objectName: db_name
          key: db_name
        - objectName: db_password
          key: db_password
        - objectName: db_port
          key: db_port
        - objectName: db_user
          key: db_user
  parameters:
    region: sa-east-1
    objects: |
      - objectName: "arn:aws:secretsmanager:sa-east-1:307946636040:secret:producao-dbcredentialsv2-sw0uGj"
        objectAlias: "producao-dbcredentialsv2"
        jmesPath:
          - path: "db_host"
            objectAlias: "db_host"
          - path: "db_name"
            objectAlias: "db_name"
          - path: "db_password"
            objectAlias: "db_password"
          - path: "db_port"
            objectAlias: "db_port"
          - path: "db_user"
            objectAlias: "db_user"
